# Generated by Django 4.2.6 on 2024-01-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_discount',
            field=models.FloatField(default=0),
        ),
    ]
