# Generated by Django 4.2.6 on 2023-12-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_city_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_total_price',
            field=models.FloatField(default=0),
        ),
    ]
